events {
    worker_connections 1024;
}

http {
    # Oculta a versão do Nginx por segurança
    server_tokens off;

    # Configurações de Segurança HTTP e CORS restrito
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    # Definindo a Zona de Limite para Mitigação de DDoS básica
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;

    server {
        listen 80;
        server_name localhost;

        # =========================================================
        # 1. UI PÚBLICA (Navegação do Usuário)
        # =========================================================
        location / {
            proxy_pass http://frontend:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # =========================================================
        # 2. ROTAS PARA O BACKEND (Acessadas EXCLUSIVAMENTE pelo Frontend)
        # O .env do Frontend apontará para essas rotas locais do Gateway
        # =========================================================
        
        # 2.1 Backend API Padrão (Front envia payloads/requests para o Back)
        location /backend/api/ {
            valid_referers server_names localhost;
            if ($invalid_referer) { return 403; }
            limit_req zone=mylimit burst=20 nodelay;

            proxy_pass http://backend:8000/api/;
            proxy_set_header Host $host;
            proxy_pass_request_headers on;
        }

        # 2.2 Backend Webhook (Front envia sinais/processos assíncronos para o Back)
        location /backend/webhook/ {
            valid_referers server_names localhost;
            if ($invalid_referer) { return 403; }

            proxy_pass http://backend:8000/webhook/;
            proxy_set_header Host $host;
            proxy_pass_request_headers on;
        }

        # =========================================================
        # 3. ROTAS PARA O FRONTEND (Acessadas EXCLUSIVAMENTE pelo Backend)
        # O .env do Backend apontará para essas rotas locais do Gateway
        # =========================================================
        
        # 3.1 Frontend API Padrão (Back envia mensagens diretas/ações requeridas ao Front)
        location /frontend/api/ {
            # Aqui, os bloqueios podem ser feitos verificando headers internos (ex. mTLS/Tokens em Python)
            proxy_pass http://frontend:3000/api/;
            proxy_set_header Host $host;
            proxy_pass_request_headers on;
        }

        # 3.2 Frontend Webhook (Back notifica eventos assíncronos que terminaram pro Front)
        location /frontend/webhook/ {
            proxy_pass http://frontend:3000/webhook/;
            proxy_set_header Host $host;
            proxy_pass_request_headers on;
        }
    }
}
